name: test
on:
  push:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_call:
jobs:
  devtools-check:
    strategy:
      # currently, we expect the addin to work with most of the same versions as flowr itself
      # see https://github.com/flowr-analysis/flowr/blob/main/.github/workflows/full-test.yaml#L20
      matrix:
        r-version: [ '4.4.0', '4.3.2', '4.2.3', '4.0.0' ]
        os: [ ubuntu-latest ]
        include:
           - os: macos-latest
             r-version: '4.4.0'
           - os: windows-latest
             r-version: '4.4.0'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools
      - name: Run devtools::check()
        # error on any type of notice from the check
        run: Rscript -e 'devtools::check(error_on = "note")'
